### ISSUE TITLE
Enable Wealth level in decision to use certain transport type

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/StopsAndStations#13]
Add possibility to select wealth levels who may use the service, for example:

Bus: low and medium wealth
Train: all wealth levels
Helicopter: high wealth

If a cim his wealth level does not match he gets rejected...

**Comment by dymanoid** [comment]
This is currently performed by the game itself or/and by other mods like TM:PE. **Stops & Stations** just tells the citizen: "no-no, you cannot use this stop", and the rest happens automatically.

**Comment by Sipke82** [comment]
Could you tell the citizen: "no-no, you cannot use this stop because you don't have enough wealth to use the helicopter. go walk or whatever, kthx bai"

Because TM:PE or other mods actually does nothing with the wealth level.

Perhaps the closest is the Lifebalance Rebalance mod, but even that mod does not decide which kind of public transport can be used by certain wealth levels..

**Comment by dymanoid** [comment]
That is actually an idea for a different mod, isn't it? I mean, the citizens behavior depending on their wealth level.

**Comment by Sipke82** [comment]
I guess it depends on the way how you look at it :-)

**Comment by dymanoid** [comment]
I am still thinking that this should be decided by other mods, not by **Stops & Stations**. Your idea is interesting though. Maybe you can post your suggestion in the [mod wish list repo](https://github.com/CitiesSkylinesMods/CitiesSkylinesModWishList).
