### ISSUE TITLE
Add off-steam installations support

### ISSUE THREAD

**Issue by complynx** [dymanoid/StopsAndStations#14]
You can do something similar to what is done here: https://github.com/bloodypenguin/Skylines-DaylightClassic/blob/master/DaylightClassic/TranslationFramework/Util.cs
They don't do searching of steam specific paths.
It's great when you have multiple installations with different path setups

**Comment by dymanoid** [comment]
This won't be implemented. The mod binaries are published only on Steam Workshop, so a subscription is required.

**Comment by complynx** [comment]
But for instance if I have subscribed but I use several installations with several mod configurations. How about that?

**Comment by dymanoid** [comment]
This is your special case then. Take the source code (it is free), change it as you like, build your own binaries.
