### ISSUE TITLE
Add a Warning

### ISSUE THREAD

**Issue by HenryLoenwind** [dymanoid/StopsAndStations#15]
Please add a warning to the Workshop page that you hate people who bought the game on Epic and have code that actively prevent them from using the mod.

If you're trying to be an a..., at least be honest about it.

**Comment by dymanoid** [comment]
Thank you for your suggestion. The mod binaries are published on Steam Workshop and are officially available only there. Steam Workshop has nothing to do with Epic. If you are not satisfied with how the mod works, you can change the source code by yourself and build your own binary. The source code is available for free for everyone.

I'm closing this issue as not planned.
